// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtuOy2XXbHz0kEvsYa5E6k-y2doTB2uY',
    appId: '1:671224991619:web:91a9f6853fa07fd6c4f0b6',
    messagingSenderId: '671224991619',
    projectId: 'todolist-6bb37',
    authDomain: 'todolist-6bb37.firebaseapp.com',
    storageBucket: 'todolist-6bb37.firebasestorage.app',
    measurementId: 'G-PV8Y3DQLH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQhSgnbA20PWgiPdw3dGYqhMcMmUZnLVo',
    appId: '1:671224991619:android:be7bcf089cdb3553c4f0b6',
    messagingSenderId: '671224991619',
    projectId: 'todolist-6bb37',
    storageBucket: 'todolist-6bb37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaxiBQxupAhGzVuDh_BFhvLNG1IWhbd2k',
    appId: '1:671224991619:ios:7e6bc0dc268d0e2bc4f0b6',
    messagingSenderId: '671224991619',
    projectId: 'todolist-6bb37',
    storageBucket: 'todolist-6bb37.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaxiBQxupAhGzVuDh_BFhvLNG1IWhbd2k',
    appId: '1:671224991619:ios:7e6bc0dc268d0e2bc4f0b6',
    messagingSenderId: '671224991619',
    projectId: 'todolist-6bb37',
    storageBucket: 'todolist-6bb37.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZtuOy2XXbHz0kEvsYa5E6k-y2doTB2uY',
    appId: '1:671224991619:web:aad35986eb941654c4f0b6',
    messagingSenderId: '671224991619',
    projectId: 'todolist-6bb37',
    authDomain: 'todolist-6bb37.firebaseapp.com',
    storageBucket: 'todolist-6bb37.firebasestorage.app',
    measurementId: 'G-15FG1BNX6C',
  );

}